# Generated by Django 5.0.4 on 2025-02-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('primer_domingo', models.BooleanField(default=False)),
                ('piano', models.CharField(default='Jose Galicia', max_length=50)),
                ('direccion_himnos', models.CharField(default='Alma Aceituno', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Obispado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('llamamiento', models.CharField(choices=[('ob', 'Obispo'), ('1c', 'Primer Consejero'), ('2c', 'Segundo Consejero'), ('sc', 'Secretario')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Obispado',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_corto', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Himno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(choices=[('1', '#1 - Ya rompe el alba'), ('2', '#2 - El Espíritu de Dios'), ('3', '#3 - Ya regocijemos'), ('4', '#4 - Bandera de Sión'), ('5', '#5 - Oh Dios de Israel'), ('6', '#6 - Israel, Jesús os llama'), ('7', '#7 - Id, vosotros mensajeros'), ('8', '#8 - ¿Qué es lo que vieron en las alturas?'), ('9', '#9 - Un ángel del Señor'), ('10', '#10 - Te damos, Señor, nuestras gracias'), ('11', '#11 - Dios manda a profetas'), ('12', '#12 - Pedimos hoy por ti'), ('13', '#13 - Bendice, Dios, a nuestro Profeta'), ('14', '#14 - La oración del Profeta'), ('15', '#15 - Loor al Profeta'), ('16', '#16 - Un pobre forastero'), ('17', '#17 - ¡Oh, está todo bien!'), ('18', '#18 - Oh Sión, santuario de libertad'), ('19', '#19 - Por Tus dones loor cantamos'), ('20', '#20 - Gozoso día llega ya'), ('21', '#21 - ¡Salve, Sión! Es tu día ilustre'), ('22', '#22 - En las cumbres de los montes'), ('23', '#23 - Bella Sión'), ('24', '#24 - El alba ya rompe'), ('25', '#25 - Jehová aparece en Su gloria'), ('26', '#26 - Hijos del Señor, venid'), ('27', '#27 - Oh Rey de reyes, ven'), ('28', '#28 - Himno de batalla de la República'), ('29', '#29 - Ven, oh día prometido'), ('30', '#30 - A Cristo Rey Jesús'), ('31', '#31 - Oh, creaciones del Señor'), ('32', '#32 - Baluarte firme es nuestro Dios'), ('33', '#33 - Honor, loor y gloria'), ('34', '#34 - Oh, Santo Dios, omnipotente ser'), ('35', '#35 - Haznos pensar en Ti, Señor'), ('36', '#36 - Padre bendito, venimos a Ti'), ('37', '#37 - Glorias cantad a Dios'), ('38', '#38 - Santos, avanzad'), ('39', '#39 - Jehová, sé nuestro guía'), ('40', '#40 - Qué firmes cimientos'), ('41', '#41 - ¡Grande eres Tú!'), ('42', '#42 - Jesús es mi luz'), ('43', '#43 - Por la belleza terrenal'), ('44', '#44 - El sublime Creador'), ('45', '#45 - Oración de gratitud'), ('46', '#46 - Elevemos nuestros himnos'), ('47', '#47 - Caros niños, Dios os ama'), ('48', '#48 - Divina Luz'), ('49', '#49 - Señor, te necesito'), ('50', '#50 - Más cerca, Dios, de ti'), ('51', '#51 - Guíame, oh Salvador'), ('52', '#52 - Guíame a Ti'), ('53', '#53 - ¡Oh Jesús, mi gran amor!'), ('54', '#54 - Paz, cálmense'), ('55', '#55 - Dios da valor'), ('56', '#56 - Jehová mi Pastor es'), ('57', '#57 - El amor del Salvador'), ('58', '#58 - Roca de eternidad'), ('59', '#59 - Mirad al Salvador'), ('60', '#60 - Venid a Cristo'), ('61', '#61 - Venid a Mí'), ('62', '#62 - No desmayéis, oh santos'), ('63', '#63 - Aunque colmados de pesar'), ('64', '#64 - Venid, los que a Dios amáis'), ('65', '#65 - ¿Sin contestar?'), ('66', '#66 - Cuán dulce la ley de Dios'), ('67', '#67 - Si la vía es penosa'), ('68', '#68 - La fe'), ('69', '#69 - ¿Dónde hallo el solaz?'), ('70', '#70 - Sé humilde'), ('71', '#71 - Más santidad dame'), ('72', '#72 - Creo en Cristo'), ('73', '#73 - Yo sé que vive mi Señor'), ('74', '#74 - Vive mi Señor'), ('75', '#75 - Testimonio'), ('76', '#76 - Tan sólo con pensar en Ti'), ('77', '#77 - Deja que el Espíritu te enseñe'), ('78', '#78 - Oh dulce, grata oración'), ('79', '#79 - La oración del alma es'), ('80', '#80 - Secreta oración'), ('81', '#81 - ¿Pensaste orar?'), ('82', '#82 - Padre en los cielos'), ('83', '#83 - Entonad sagrado son'), ('84', '#84 - Dulce Tu obra es, Señor'), ('85', '#85 - El día santo del Señor'), ('86', '#86 - Nuestro bondadoso Padre'), ('87', '#87 - Cual rocío, que destila'), ('88', '#88 - Placentero nos es trabajar'), ('89', '#89 - Para siempre Dios esté con Vos'), ('90', '#90 - Padre, antes de partir'), ('91', '#91 - Al partir cantemos'), ('92', '#92 - Hemos sentido Tu amor'), ('93', '#93 - A Ti, Señor'), ('94', '#94 - Ya termina el día'), ('95', '#95 - El fuego del Espíritu'), ('96', '#96 - El ocaso viene ya'), ('97', '#97 - Ante Ti, Señor, Tu grey'), ('98', '#98 - Conmigo quédate, Señor'), ('99', '#99 - Acompáñame'), ('100', '#100 - Dios, bendícenos'), ('101', '#101 - Dios, escúchanos orar'), ('102', '#102 - Hoy con humildad te pido'), ('103', '#103 - La Santa Cena'), ('104', '#104 - Oh Dios, Eterno Padre'), ('105', '#105 - Jesús de Nazaret'), ('106', '#106 - Cuán grato es cantar loor'), ('107', '#107 - Pedimos Tu Espíritu'), ('108', '#108 - Mansos, reverentes hoy'), ('109', '#109 - Cantemos todos a Jesús'), ('110', '#110 - En memoria de Tu muerte'), ('111', '#111 - En el Calvario, en la cruz'), ('112', '#112 - El Padre tanto nos amó'), ('113', '#113 - Ya nos juntamos otra vez'), ('114', '#114 - Cristo, el Redentor, murió'), ('115', '#115 - Nos reunimos, Padre, hoy'), ('116', '#116 - Jesús, en la corte celestial'), ('117', '#117 - ¡Murió! El Redentor murió'), ('118', '#118 - Asombro me da'), ('119', '#119 - En un lejano cerro fue'), ('120', '#120 - Tan humilde al nacer'), ('121', '#121 - Himno de la Pascua de Resurrección'), ('122', '#122 - Cristo ha resucitado'), ('123', '#123 - ¡Regocijad! Jesús nació'), ('124', '#124 - Venid, adoremos'), ('125', '#125 - Jesús en pesebre'), ('126', '#126 - Cantan santos ángeles'), ('127', '#127 - Noche de luz'), ('128', '#128 - A medianoche se oyó'), ('129', '#129 - Oh, pueblecito de Belén'), ('130', '#130 - Escuchad el son triunfal'), ('131', '#131 - Asombro dio a los magos'), ('132', '#132 - La primera Navidad'), ('133', '#133 - Campanas de Navidad'), ('134', '#134 - En la Judea, en tierra de Dios'), ('135', '#135 - Hoy sembramos la semilla'), ('136', '#136 - Todos los santos'), ('137', '#137 - Tú me has dado muchas bendiciones, Dios'), ('138', '#138 - Señor, yo te seguiré'), ('139', '#139 - Ama el Pastor las ovejas'), ('140', '#140 - A Dios el Padre y a Jesús'), ('141', '#141 - ¿En el mundo he hecho bien?'), ('142', '#142 - Otro año ha pasado'), ('143', '#143 - A Dios ofrecemos gozosa canción'), ('144', '#144 - A la gloria marcharemos'), ('145', '#145 - La voz, ya, del eterno'), ('146', '#146 - Tengo gozo en mi alma hoy'), ('147', '#147 - Recojamos los destellos'), ('148', '#148 - Si hay gozo en tu corazón'), ('149', '#149 - Trabajad con fervor'), ('150', '#150 - Siembra gozo'), ('151', '#151 - Oh, hablemos con tiernos acentos'), ('152', '#152 - No hablemos con enojo'), ('153', '#153 - Oíd el toque del clarín'), ('154', '#154 - Haz tú lo justo'), ('155', '#155 - Haz el bien'), ('156', '#156 - Señor del cielo, Jehová'), ('157', '#157 - Cuenta tus bendiciones'), ('158', '#158 - Trabajemos hoy en la obra'), ('159', '#159 - Con valor marchemos'), ('160', '#160 - Tu casa amamos, Dios'), ('161', '#161 - Llamados a servir'), ('162', '#162 - Somos los soldados'), ('163', '#163 - ¡Mirad! Reales huestes'), ('164', '#164 - Pon tu hombro a la lid'), ('165', '#165 - Tu palabra'), ('166', '#166 - Firmes creced en la fe'), ('167', '#167 - A vencer'), ('168', '#168 - Juventud de Israel'), ('169', '#169 - Al mundo ve a predicar'), ('170', '#170 - ¿Quién sigue al Señor?'), ('171', '#171 - La luz de la verdad'), ('172', '#172 - Cuando enseñe a Tus hijos'), ('173', '#173 - El fin se acerca'), ('174', '#174 - Qué maravillosas Tus obras'), ('175', '#175 - A donde me mandes iré'), ('176', '#176 - Palabras de amor'), ('177', '#177 - ¿Qué es la verdad?'), ('178', '#178 - Nuestra mente se refleja'), ('179', '#179 - La barra de hierro'), ('180', '#180 - Al leer las Escrituras'), ('181', '#181 - Cuando raya el nuevo dia'), ('182', '#182 - Bienvenido, día santo'), ('183', '#183 - Santos templos de Sión'), ('184', '#184 - Id, oh santos, a los templos'), ('185', '#185 - En los postreros días'), ('186', '#186 - Volved vuestro corazón'), ('187', '#187 - Oh mi Padre'), ('188', '#188 - Quienes nos brindan su amor'), ('189', '#189 - Oh Padre, llénanos de amor'), ('190', '#190 - Hay un hogar eterno'), ('191', '#191 - Con maravillas obra Dios'), ('192', '#192 - ¿Por qué somos?'), ('193', '#193 - El hogar es como el cielo'), ('194', '#194 - Cuando hay amor'), ('195', '#195 - Las familias pueden ser eternas'), ('196', '#196 - Soy un hijo de Dios'), ('197', '#197 - Siempre obedece los mandamientos'), ('198', '#198 - Hazme andar en la luz'), ('199', '#199 - Dios vive'), ('200', '#200 - La luz de Dios'), ('201', '#201 - Dios cuida a sus hijos'), ('202', '#202 - En el pueblo de Sión'), ('203', '#203 - Amad a otros'), ('204', '#204 - Hijos de nuestro Padre'), ('205', '#205 - Sirvamos unidas (Mujeres)'), ('206', '#206 - Venid, los que tenéis de Dios el sacerdocio (Hombres)'), ('207', '#207 - Oh vos que sois llamados (Hombres)'), ('208', '#208 - Brillan rayos de clemencia (Hombres)'), ('209', '#209 - Oh élderes de Israel (Hombres)'), ('210', '#1001 - Fuente de mis bendiciones'), ('211', '#1002 - Cuando vuelva el Salvador'), ('212', '#1003 - Reina paz en mi ser'), ('213', '#1004 - Andaré con Cristo'), ('214', '#1005 - Él cuida de las aves'), ('215', '#1006 - En tu corazón entona una cancion'), ('216', '#1007 - En Ti pensamos'), ('217', '#1008 - Agua viva, pan de vida'), ('218', '#1009 - Getsemaní'), ('219', '#1010 - Sublime Gracia'), ('220', '#1011 - Somos niños, de la mano del Señor'), ('221', '#1012 - En cualquier ocasión'), ('222', '#1013 - Dios me da Su Gracia'), ('223', '#1014 - Mi buen pastor es Jehová'), ('224', '#1015 - Oh, cuán pleno, cuán profundo'), ('225', '#1016 - Mirad las marcas de Jesús'), ('226', '#1017 - El Cristo es'), ('227', '#1018 - Ven, oh, Cristo'), ('228', '#1201 - Gloria al dia de redención'), ('229', '#1202 - El divino Jesús nació'), ('230', '#1203 - Que niño es este?'), ('231', '#1204 - Estrella de luz')], max_length=50)),
                ('tipo', models.CharField(choices=[('1er', 'Himno inicial'), ('2do', 'Himno Sacramental'), ('3er', 'Himno intermedio'), ('4to', 'Himno final'), ('pre', 'Preludio'), ('pos', 'Posludio'), ('esp', 'Himno Especial')], max_length=3)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Discurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50)),
                ('cofirmado', models.BooleanField(default=False)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agenda')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('quien_realiza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obispado')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='dirige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirige', to='api.obispado'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='preside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preside', to='api.obispado'),
        ),
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('primera', 'Primera Oracion'), ('final', 'Oracion Final')], max_length=10)),
                ('confirmado', models.BooleanField(default=False)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Limpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('finalizada', models.BooleanField()),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agenda')),
                ('organizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizacion')),
            ],
            options={
                'verbose_name_plural': 'Limpieza',
            },
        ),
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('agenda', models.ManyToManyField(blank=True, to='api.agenda')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obispado')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('presupuesto', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('agenda', models.ManyToManyField(blank=True, to='api.agenda')),
                ('organizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizacion')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Templo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('reserva_confirmada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('agenda', models.ManyToManyField(blank=True, to='api.agenda')),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obispado')),
            ],
            options={
                'verbose_name_plural': 'Templo',
            },
        ),
    ]
