# Generated by Django 5.0.4 on 2025-02-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_oracion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discurso',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.miembro'),
        ),
    ]
