# Generated by Django 5.0.4 on 2025-02-11 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_discurso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discurso',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.miembro'),
        ),
        migrations.AlterField(
            model_name='oracion',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.miembro'),
        ),
    ]
