# Generated by Django 5.0.4 on 2024-04-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_oracion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracion',
            name='fecha',
        ),
    ]
