# Generated by Django 5.0.4 on 2025-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_discurso_nombre_alter_oracion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(default='Capilla pinares 1', max_length=100),
            preserve_default=False,
        ),
    ]
