# Generated by Django 5.0.4 on 2024-04-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_oracion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracion',
            name='fecha',
        ),
    ]
