# Generated by Django 5.0.4 on 2024-04-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agenda_primer_domingo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='codigo',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
