# Generated by Django 5.0.4 on 2024-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_templo_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templo',
            name='agenda',
        ),
        migrations.AddField(
            model_name='templo',
            name='agenda',
            field=models.ManyToManyField(blank=True, to='api.agenda'),
        ),
    ]
