# Generated by Django 5.0.4 on 2024-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_templo_agenda_templo_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20)),
                ('key', models.CharField(default='Ypw86Sq4K9FHRFDzvmojVbDisPtG0Wj2', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='oracion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('primera', 'Primera Oracion'), ('final', 'Oracion Final')], max_length=10),
        ),
    ]
