# Generated by Django 5.0.4 on 2024-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_authtoken_alter_oracion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(default='fqxxhVaRV2NElYZuHAH6TYmqWGAtOJhi', max_length=32),
        ),
    ]
